version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pg_pass
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - 8000:8000
    expose:
      - 8000
    stdin_open: true
    tty: true
    depends_on:
      - db

  nginx:
    depends_on:
      - backend
    restart: always
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    expose:
      - 3050
    ports:
      - "3050:80"

volumes:
  postgres_volume:
    driver: local
